### PR TITLE
fixing kernel driver module path

### PR DESCRIPTION
**Pull request by bmichalo**

### CODE REVIEW

**Comment by atheurer** [comment]
Why does the "kernel driver in use" need to be used instead of "kernel modules"?  In what case does "kernel modules" not provide the right result?

**Comment by bmichalo** [comment]
]# lspci -k -s 0000:00:06.0
00:06.0 Ethernet controller: Red Hat, Inc. Virtio network device
	Subsystem: Red Hat, Inc. Device 0001
	Kernel driver in use: virtio-pci
	Kernel modules: virtio_pci

kernel modules parsing yields "virtio_pci", while parsing "kernel driver in use" provides the correct name for the path that includes "virtio-pci".

# lspci -k -s 0000:00:06.0 | grep "Kernel modules:" | awk -F": " '{print $2}'
virtio_pci

# lspci -k -s 0000:00:06.0 | grep "Kernel driver in use:" | awk -F": " '{print $2}'
virtio-pci

**Comment by atheurer** [comment]
OK, I have to check if this works when using modules other than vfio

**Comment by atheurer** [comment]
So, if the module is not already loaded, then "kernel driver in use" is not present in the output of lspci, and that's what I was worried about.  We use $kernel_nic_kmod elsewhere to know what is the kernel module needed for a specific network card, in the case for linuxbridge or ovs-hw-offload, and if the right kernel module is not already loaded, or a different module is in use, like vfio, then the "Kernel driver in use" result will be incorrect.  So, I am not sure if we can use this change.  I think the core issue is why does one have "_" and the other have "-".  It makes no sense at all.  Maybe we need to have 2 variables, one for the actual module name, $kernel_nic_kmod, that uses "_", and another, $kernel_nic_sysfs_name, that uses "-".  I need to see if virtio is the only one like this or if others have this issue.

**Comment by atheurer** [comment]
Hmm, this latest commit is a bit confusing...  I think it might be easier to drop this PR and re-submit a new one

**Comment by atheurer** [comment]
I have fixed this issue in commit https://github.com/atheurer/dpdk-rhel-perf-tools/commit/d73216c3129a9695f5965ff8737c8aa10adc6ca1

**Pull request closed without merging**
